### ISSUE TITLE
`An exception occured in node` in `remuneration_apprenti` and `taux_versement_transport`

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-parsers#5]
When iterating over all columns in the Swagger API, only `remuneration_apprenti` and `taux_versement_transport` log an error. It does not seem to impact the parser behaviour, but I thought it might be of interest to @eraviart to exhaustively list the failing nodes  :)

**Comment by fpagnoux** [comment]
This package is deprecated. This issue won't be addressed, sorry.
