### ISSUE TITLE
Delete "one-shot" scripts?

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-parsers#8]
@eraviart Should I delete old scripts meant to be executed once, like [formulas_functions_to_classes.py](https://github.com/openfisca/openfisca-parsers/blob/master/openfisca_parsers/scripts/formulas_functions_to_classes.py) or [formulas_parameters_to_variables.py](https://github.com/openfisca/openfisca-parsers/blob/master/openfisca_parsers/scripts/formulas_parameters_to_variables.py)

Now that the sources are updated everywhere these scripts seem obsolete (?)

**Comment by MattiSG** [comment]
:+1:

**Comment by cbenz** [comment]
The answer is yes
